### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [franekostrowski/diveholic#26]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by franekostrowski** [comment]
Hi! Thanks for checking out the project and your suggestion. I'll go ahead and add the MIT License to the project.
I haven't had much time for improvements lately and must've missed your PR, sorry for that! 
Feel free to reach out if you have more thoughts in the future!

Cheers,
Franek
